version: '2'

services:
    es-client:
        ports: 
            - "9200:9200"
    logstash:
        volumes:
            - ./configuration:/config-dir/
        command: logstash -f ./config-dir/logstash.conf

networks:
    elk-network: