version: '2'

services:
    es-master:
        networks:
        - metrics-network

    es-data:
        networks:
        - metrics-network

    es-client:
        networks:
        - metrics-network

    kibana:
        networks: 
        - metrics-network

    logstash:
        image: pblittle/docker-logstash
        command: logstash -e LOGSTASH_CONFIG_URL=https://raw.githubusercontent.com/3shapeAS/Communicate.Configuration/staging/Elasticsearch-Logstash-Kibana/configuration/logstash.conf
        networks: 
        - metrics-network
            
networks:
  metrics-network:
    driver: overlay