version: '2'

services:
    es-master:
        image: elasticsearch:2
        restart: always
        command: elasticsearch --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping.unicast.hosts=es-master --discovery.zen.minimum_master_nodes=3 --node.master=true --node.data=false --cluster.name=metrics --node.name=es-master --network.bind_host=0.0.0.0
        networks:
        - elk-network
        environment:                                                                                                                                                                                                                                                                                        
        - reschedule=on-node-failure
        labels:
        - 'com.docker.swarm.reschedule-policies=["on-node-failure"]'

    es-data:
        image: elasticsearch:2
        command: elasticsearch --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping.unicast.hosts=es-master --discovery.zen.minimum_master_nodes=3 --node.master=false --node.data=true --cluster.name=metrics --node.name=es-data
        restart: always
        depends_on:
            - es-master
        networks:
        - elk-network

    es-client:
        image: elasticsearch:2
        command: elasticsearch --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping.unicast.hosts=es-master --discovery.zen.minimum_master_nodes=3 --node.master=false --node.data=false --cluster.name=metrics --node.name=es-client
        restart: always
        depends_on:
            - es-master
        networks:
        - elk-network

    kibana:
        image: kibana
        ports: 
            - "5601:5601"
        command: kibana --elasticsearch.url=http://es-client:9200
        restart: always
        depends_on: 
            - es-client
        networks: 
        - elk-network

    logstash:
        image: logstash
        ports:          
            - "5044:5044"
        command: logstash -e 'input { beats { port => 5044 }} filter { if [message] =~ /^#/ { drop{} } grok { match => { "message" => "(?<timestampIIS>%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:%{MINUTE}:%{SECOND}) \w+ \w+ %{IPV4:ip} (?<httpmethod>GET|POST|PUT) %{URIPATH:url} .* (?<httpstatus>[0-9]{3}) \d+ \d+ \d+ \d+ %{INT:timetaken:int}" } match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{IPV4:ip} %{WORD:httpmethod} %{URIPATH:url} .* - %{INT:httpstatus:int} \d+ \d+ %{INT:timetaken:int}" } match => { "message" => "%{TIMESTAMP_ISO8601:timestamp}[\t](?<httpMethod>GET|POST)[\t]%{IPV4:requestIp}[\t]%{INT:size:int}[\t]%{INT:timetaken:int}" } match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \w+ \w+ %{IPV4:ip} (?<httpmethod>GET|POST|PUT) %{URIPATH:url} .* (?<httpstatus>[0-9]{3}) \d+ \d+ \d+ \d+ %{INT:timetaken:int}" } match => { "message" => "%{TIMESTAMP_ISO8601:timestamp}[\t]%{WORD:CaseId}[\t]%{WORD:method}[\t]%{INT:timetaken:int}" } } date { match => ["timestampIIS", "YYYY-MM-dd HH:mm:ss", "ISO8601"] } } output { elasticsearch { hosts => ["es-client"] index => "%{type}-%{+YYYY.MM.dd}" } }'
        depends_on: 
            - es-client
        networks: 
        - elk-network
      

networks:
  elk-network:
    driver: overlay